### 

POST http://localhost:4000/horario/agregarHorarios HTTP/1.1
Content-Type: application/json

{
    "Dia_semana": "viernes",
    "Hora_inicio": "15:15",
    "Hora_fin": "16:30",
    "Lugar": "Salon4"
}

###

GET http://localhost:4000/horario/opsionesActividad HTTP/1.1

### 

POST http://localhost:4000/horario/agregarHorariosActividad HTTP/1.1
Content-Type: application/json

{
    "id_actividad": 1,
    "horario_id": 7
}

###

GET http://localhost:4000/horario/filtroHorarios HTTP/1.1

###

GET  http://localhost:4000/horario/buscarHorarios/Salon4/lunes HTTP/1.1


###

PUT http://localhost:4000/horario/actualizarHorario/8 HTTP/1.1
Content-Type: application/json

{
    "Dia_semana": "sabado",
    "Hora_inicio": "18:23:00",
    "Hora_fin": "15:30:00",
    "Lugar": "salon4"
}

###

DELETE http://localhost:4000/horario/eliminarHorario/8 HTTP/1.1

###

GET  http://localhost:4000/horario/VerCronograma/lunes HTTP/1.1

###

POST http://localhost:4000/ingresar HTTP/1.1
Content-Type: application/json

{
    "correo": "torresCruz843@gmail.com",
    "contrasena": "CruzT87"
}


###

DELETE http://localhost:4000/horario/EliminarActividadHorario/2/1 HTTP/1.1